// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRMikW0sxtnNk2tLESxYl_f_b8T6j2jLg',
    appId: '1:704139293800:android:7265cd0871e6d1c434f7dd',
    messagingSenderId: '704139293800',
    projectId: 'todolist-425914',
    databaseURL: 'https://todolist-425914-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-425914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrNNoOIdpAM4q-Dtw04TZYLqFow6QdG0A',
    appId: '1:704139293800:ios:246071495ecd7b4734f7dd',
    messagingSenderId: '704139293800',
    projectId: 'todolist-425914',
    databaseURL: 'https://todolist-425914-default-rtdb.firebaseio.com',
    storageBucket: 'todolist-425914.appspot.com',
    androidClientId: '704139293800-csk48e7k9c90q8oo0otnmlgfkd86ck05.apps.googleusercontent.com',
    iosBundleId: 'com.shangchianliu.todilist',
  );

}